@startuml

class Client { }

interface Handler {
    + handleRequest()
}

class ConcreteHandler1 {
    + handleRequest()
}

class ConcreteHandler2{
    + handleRequest()
}

Client --> Handler
Handler <-- "sucessor" Handler
Handler ^-- ConcreteHandler1
Handler ^-- ConcreteHandler2

@enduml
